# Generated by Django 3.2.3 on 2021-05-26 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_delete_shipping_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=30)),
                ('House', models.CharField(max_length=30)),
                ('Apartment', models.CharField(max_length=30)),
                ('Zip', models.CharField(blank=True, max_length=6)),
                ('Town', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Additional_Information', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
