# Generated by Django 3.2.3 on 2021-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_billing_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_adress',
            name='Additional_Information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billing_adress',
            name='Apartment',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='billing_adress',
            name='Company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
